# Generated by Django 3.1.4 on 2021-01-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='texts',
            name='klaccName',
            field=models.TextField(db_column='klaccNmame', default=0, unique=True),
            preserve_default=False,
        ),
    ]
